version: '3.8'
services:
  postgres-db:
    image: postgres:14
    container_name: sales-service-db
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sales-db
    networks:
      - tenderi

networks:
  tenderi:
    driver: bridge
